site_name: EGR314 Team 302 - R6 Recon Amphibot
site_url: https://egr314-s-2026-302.github.io/EGR314-Team302.github.io/
repo_url: https://github.com/egr314-s-2026-302/EGR314-Team302.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  logo: static/logo-314.svg
  favicon: static/logo_314.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2026 Team XPED - Team 302 EGR314"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/egr314-s-2026-302/EGR314-Team302.github.io
      name: Team 302 on GitHub